CREATE TABLE funcionario (
    idfuncionario INT AUTO_INCREMENT,
    nome VARCHAR(45),
    sobrenome VARCHAR(45),
    pis VARCHAR(45),
    cpf VARCHAR(45),
    rg VARCHAR(45),
    expedicao_rg DATE,
    emissor_rg VARCHAR(45),
    uf_rg VARCHAR(45),
    carteira_motorista VARCHAR(45),
    categoria_cnh VARCHAR(45),
    expedicao_cnh DATE,
    validade_cnh DATE,
    carteira_trabalho VARCHAR(45),
    serie_ctps VARCHAR(45),
    uf_ctps VARCHAR(45),
    titulo_eleitor VARCHAR(45),
    nascimento DATE,
    nacionalidade VARCHAR(45),
    cep VARCHAR(45),
    estado VARCHAR(45),
    bairro VARCHAR(45),
    cidade VARCHAR(45),
    endereco VARCHAR(45),
    sexo VARCHAR(45),
    estado_civil VARCHAR(45),
    mae VARCHAR(45),
    pai VARCHAR(45),
    cracha VARCHAR(45),
    telefone VARCHAR(45),
    admissao DATE,
    demissao DATE,
    status VARCHAR(45),
    motivo_demissao VARCHAR(45),
    departamento VARCHAR(45),
    cargo VARCHAR(45),
    cargo_descricao VARCHAR(45),
    idperiodo INT,
    exame_admissional DATE,
    periodo_experiencia VARCHAR(45),
    primeiro_emprego VARCHAR(45),
    contribuicao_social VARCHAR(45),
    idadmissao INT,
    vinculo VARCHAR(45),
    salario DECIMAL(10,2),
    banco VARCHAR(45),
    agencia VARCHAR(45),
    conta VARCHAR(45),
    email_google VARCHAR(45),
    email_hotmail VARCHAR(45),
    local_exame VARCHAR(45),
    url_image VARCHAR(45),
    empresa_idempresa INT,
    periodo_idperiodo INT,
    PRIMARY KEY (idfuncionario),
    FOREIGN KEY (empresa_idempresa) REFERENCES empress(idempresa),
    FOREIGN KEY (periodo_idperiodo) REFERENCES periodo(idperiodo)
);