CREATE TABLE falta (
    idfaltas INT AUTO_INCREMENT,
    data DATE,
    dias DECIMAL(10,2),
    horas DECIMAL(10,2),
    lancamento TIMESTAMP,
    motivo VARCHAR(45),
    tipo VARCHAR(45),
    medico VARCHAR(45),
    mes INT,
    ano VARCHAR(45),
    idcid INT,
    descricao_cid VARCHAR(45),
    data_inicial DATE,
    data_final DATE,
    hora_inicial TIME,
    hora_final TIME,
    duracao VARCHAR(45),
    retorno DATE,
    idfuncionario INT,
    funcionario_nome VARCHAR(45),
    departamento VARCHAR(45),
    idfilial INT,
    idlembrete INT,
    funcionario_idfuncionario INT,
    PRIMARY KEY (idfaltas),
    FOREIGN KEY (funcionario_idfuncionario) REFERENCES funcionario(idfuncionario)
);