CREATE TABLE absence (
    id INT AUTO_INCREMENT,
    date DATE,
    days DECIMAL(10,2),
    hours DECIMAL(10,2),
    record TIMESTAMP,
    reason VARCHAR(45),
    type VARCHAR(45),
    doctor VARCHAR(45),
    month INT,
    year VARCHAR(45),
    cid_id INT,
    cid_description VARCHAR(45),
    start_date DATE,
    end_date DATE,
    start_time TIME,
    end_time TIME,
    duration VARCHAR(45),
    return_date DATE,
    idemployee INT,
    employee_name VARCHAR(45),
    department VARCHAR(45),
    branch_id INT,
    reminder_id INT,
    employee_id INT,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES employee(id)
);